### ISSUE TITLE
[Suggestion] Development Assistance

### ISSUE THREAD

**Issue by raymondbh** [Deadrik/TFC2#12]
If you need any help developing code/content for TFC2, maybe make cases here, and people wanting to help can "pick" different tasks you want to have done... I know we are a handful of people wanting to help... :-)

**Comment by MCrafterzz** [comment]
You could always create a pull request 😃

**Comment by raymondbh** [comment]
Hello Bioxx. Anything the community can do to help you with the dev of TFC2? :-)
