### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by MarcusElg** [Deadrik/TFC2#14]
1. Will the worldgen be big hexagons as it is now?
2. When the addon systems allows you to add new blocks etc will you use it or will you just continue with the java version?

**Comment by sirStroam** [comment]
Yes, they've stated in the forums that they will go forward with the hex.

**Comment by Deadrik** [comment]
I highly doubt that I'll be using whatever sorry excuse for a mod system that Mojang comes up with unless Forge stops development, and even then I'd probably just not use newer MC versions, or stop development entirely.
