### ISSUE TITLE
Ressrouce

### ISSUE THREAD

**Issue by aliceingame** [Deadrik/TFC2#15]
It seems that this commit changed the name of all the content of the asset folder (to lowercase), creating a doulble of every file that had a name with a capital letter.

https://github.com/Deadrik/TFC2/commit/6095a306707d547a580abe226fadb84f9555d9b3

**Comment by Deadrik** [comment]
Well isn't that just annoying :/ No clue how we're going to fix that honestly.

**Comment by Kittychanley** [comment]
Fixing it now. Silly windows not being case sensitive.
