### ISSUE TITLE
Is this repo even actual?

### ISSUE THREAD

**Issue by bsun0000** [Deadrik/TFC2#17]
Found this on twitter:

> Ported to 1.11, still have some weird issues to fix. Might do an Alpha release sometime soon.
Posted on Mar. 9, today is Mar. 21 and looks like "soon" is not going to happen.. :(

So i have a question - can i use sources from this repository to compile TFC2 on my own or this is a waste of a time? I'm not java programmer, but i tried to compile this mod and got some weird errors:

One in **asm/transform/ModuleFood.java**, on line 61 (two arguments passed to ObfHelper.getDescriptor, meanwhile this function accepts only one) and second one after i finally compile TFC, on game startup:

>java.lang.NoClassDefFoundError: net/minecraft/item/ItemFishFood
>...
>net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: 
>Exception in class transformer com.bioxx.tfc2.asm.transform.ModuleFood@ec16f8 from coremod >TFCASMLoadingPlugin
>...
>java.lang.RuntimeException: ItemFishFood: getSubItems (a) method not found

I did something wrong (tried to run on 1.11.2mc) or TFC2 is still not ready even for a compiling & testing?

**Comment by Kittychanley** [comment]
"soon" is usually at least a month. There's probably still compiler errors from the port that we haven't fixed yet.

**Comment by Precision-Smelter** [comment]
Yes, this repo will compile and run under Minecraft 1.11.2 (Forge 1.11.2-13.20.0.2228) after these 4 edits:

1) File "src\ASM\com\bioxx\tfc2\asm\transform\ModuleFood.java"  +++Replace line 61 with:
   String methDesc = ASMHelper.toMethodDescriptor("V", ObfHelper.toObfClassName(ASMConstants.ITEM), ObfHelper.toObfClassName(ASMConstants.CREATIVETABS), ObfHelper.toObfClassName(ASMConstants.NONNULLLIST), ObfHelper.toObfClassName(ASMConstants.ITEMSTACK));

2) File "src\ASM\com\bioxx\tfc2\asm\transform\ModuleFood.java"  +++Replace line 89 with:
   ;

3) File "src\ASM\com\bioxx\tfc2\asm\transform\ModuleEntityRenderer.java"  +++Replace line 32 with:
   ;

4) File "src\ASM\com\bioxx\tfc2\asm\transform\ModuleEntityRenderer.java"  +++Add line 33:
   return basicClass;

It is obviously still WIP, so it's quite unstable, but it will run.

BTW, I love all the new animals! :)
