### ISSUE TITLE
FYI: missing com.bioxx.tfc2.api.heat.ItemHeat

### ISSUE THREAD

**Issue by CHeuberger** [Deadrik/TFC2#21]
more a comment than an Issue:
seems like the package com.bioxx.tfc2.api.heat is missing - its class ItemHeat is being imported in com.bioxx.tfc2.ClientOverrides.

Not a big deal since it is not being used, but I just wanted to inform that probably the whole directory was not (yet) added to the repository.

**Comment by Deadrik** [comment]
Just a screwup on my part when selectively pushing lines.
