### ISSUE TITLE
"IndexOutOfBoundsException" sponge + forge

### ISSUE THREAD

**Issue by MixSt** [Deadrik/TFC2#27]
Hi! I tried to create server with spongeforge-1.11.2-2282-6.0.0-BETA-2287
and forge-1.11.2-13.20.0.2284.
And then i try to login, i take a server error: [https://pastebin.com/qrqJgN62](https://pastebin.com/qrqJgN62)

All works fine without sponge.

**Comment by raymondbh** [comment]
"All works fine without sponge." ... so why are you posting a Sponge error here?

Sorry, could not help myself.

**Comment by Deadrik** [comment]
Closing since this doesn't seem to be related to tfc2 at all.
